[package]
name = "chip_desktop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chip_core = { path = "../chip_core" }

cpal = "0.15"
softbuffer = "0.4"
tinyaudio = "0.1"
winit = "0.29"
